import type { VibeLabel } from "@/lib/types"

export interface PersonalityProfile {
  archetype: string
  tagline: string
  strengths: [string, string, string]
  weaknesses: [string, string, string]
  habits: string[]
  improvements: string[]
  roasts: string[]
  compliments: string[]
}

const PROFILES: Record<VibeLabel, PersonalityProfile> = {
  "Chaotic Genius": {
    archetype: "The Mad Scientist",
    tagline: "You don't follow the plan. You ARE the plan.",
    strengths: [
      "Incredible creative problem-solving — you find solutions nobody else would think of",
      "High velocity — you ship faster than most teams combined",
      "Fearless experimentation — you're not afraid to try wild approaches",
    ],
    weaknesses: [
      "Your codebase looks like a crime scene with no witnesses",
      "Documentation is something that happens to other people",
      "You context-switch so fast even your AI agent gets whiplash",
    ],
    habits: [
      "Starts 5 features before finishing 1",
      "Renames variables mid-conversation because the first name 'didn't feel right'",
      "Has conversations with AI at 2am about architecture decisions that won't matter in a week",
      "Abandons branches like they're going out of style",
    ],
    improvements: [
      "Finish one thing before starting the next — your future self will thank you",
      "Write a README before you forget what your own code does",
      "Commit more often — your git history shouldn't read like a novel",
    ],
    roasts: [
      "Your git log reads like a fever dream written by someone who just discovered energy drinks.",
      "You've refactored your project structure more times than you've actually shipped features.",
      "Your AI agent has filed a restraining order against your 3am coding sessions.",
      "You don't have technical debt — you have a technical mortgage, a technical car loan, and a technical credit card balance.",
      "Your commit messages are just variations of 'fixed stuff' and 'okay this time for real'.",
      "You treat your codebase like a whiteboard — everything is temporary, including the production code.",
      "Your branch strategy is 'create one, forget about it, create another one, repeat'.",
      "You've said 'I'll clean this up later' so many times it should be your LinkedIn headline.",
      "Your abandoned branches outnumber your merged ones by a ratio that would concern any therapist.",
      "You've deleted and recreated the same file so many times git thinks it's a different project.",
      "Your AI agent has seen more unfinished projects than a venture capitalist's inbox.",
      "You once rewrote an entire module because you didn't like the font the AI used in the code comments. There is no font in code comments.",
      "Your idea of version control is saving copies named 'final', 'final_v2', 'final_ACTUAL_final'.",
      "You've started more side projects this week than most developers start in a year. You've finished zero of them.",
      "Your workspace has more open tabs than a browser on its last legs.",
      "You've rage-quit a feature only to restart it with the exact same approach 20 minutes later.",
      "Your AI agent has learned to say 'are you sure about this?' and you always say yes. You're never sure.",
      "You write TODO comments like you're writing letters to a future civilization.",
      "Your architecture diagrams look like conspiracy theory boards with red string.",
      "You've npm-init'd more projects today than you've git-pushed in the last month.",
      "Your .gitignore file is the most carefully maintained file in your entire repository.",
      "You've asked your AI to 'just try something wild' and then been surprised when it did.",
      "Your stash list is longer than most people's commit history.",
      "You context-switch so hard your CPU is jealous of your throughput.",
      "You've mass-commented out working code to 'try a different approach' and never uncommented it.",
      "Your code has more experimental branches than a pharmaceutical company.",
      "You treat dependency versions like suggestions, not requirements.",
      "Your AI agent has started prefacing responses with 'I know you're going to change your mind, but...'",
      "Your pull requests have more changed files than your project has total files.",
      "You've invented three new design patterns this week. None of them should exist.",
      "You've interrupted your AI mid-response so many times it's developed anticipatory anxiety.",
      "Your 'quick fix' commits are neither quick nor fixes.",
      "You've renamed your project four times and it's still in the scaffolding phase.",
      "Your coding sessions are like jazz — no structure, lots of improvisation, and confusing to anyone watching.",
      "You treat every new framework release as a reason to rewrite everything from scratch.",
      "Your IDE's 'undo' button files for overtime every sprint.",
      "You've written more configuration files than actual application code.",
      "Your git blame looks like a randomized experiment in authorship attribution.",
      "You've started debugging something, gotten distracted, and accidentally built an unrelated feature.",
      "Your AI agent doesn't know if it's helping you build a web app, a CLI tool, or a game. Neither do you.",
      "Your local environment has environment variables from three different projects that somehow don't conflict. Yet.",
      "You once spent an hour arguing with your AI about the best way to do something, then did it a third way.",
      "Your dead code is the most stable part of your application.",
      "You treat 'git rebase' like a recreational activity.",
      "You've created a utility function, used it once, forgotten about it, and recreated it under a different name.",
      "Your project has more README drafts than deployments.",
      "You've force-pushed to main 'just this once' more times than you've written tests.",
      "Your coding playlist has more songs than your test suite has assertions.",
      "You don't debug — you just rewrite the whole thing and hope the bug was in the part you changed.",
      "Your AI agent's context window fills up just from the things you've asked it to undo today.",
    ],
    compliments: [
      "You see connections and possibilities that other developers completely miss. That's a genuine superpower.",
      "Your ability to prototype and iterate at speed is genuinely impressive — most teams would kill for your velocity.",
      "You're the person people call when something 'impossible' needs to get done by Friday.",
      "Your creativity with AI tools is ahead of the curve — you're using them in ways most people haven't figured out yet.",
      "When you finally focus on one thing, the results are genuinely exceptional.",
      "You're not chaotic — you're just operating at a frequency most people can't keep up with.",
      "Your willingness to throw away code and start fresh is actually a sign of maturity most developers lack.",
      "You have an instinct for emerging patterns and technologies that consistently puts you ahead of the curve.",
      "Your rapid experimentation produces more learnings in a week than most developers get in a month.",
      "The energy you bring to a project is contagious — you make other people want to build things.",
      "You're not afraid to look foolish trying something new. That courage is how breakthroughs happen.",
      "Your ability to hold multiple complex systems in your head simultaneously is genuinely rare.",
      "When the team is stuck, your wild ideas are often what break the deadlock.",
      "You understand intuitively that software is iterative — your many attempts aren't failures, they're research.",
      "Your creative problem-solving saves teams from getting stuck in conventional thinking.",
      "You have a talent for finding the unexpected solution that's simpler than what everyone else was planning.",
      "Your comfort with ambiguity makes you invaluable in early-stage projects where nothing is defined yet.",
      "You generate more ideas before lunch than most teams generate in a sprint planning session.",
      "Your pattern recognition across different domains gives you a unique perspective that pure specialists lack.",
      "The breadth of technologies you've experimented with gives you an unusually wide solution space.",
      "You have a natural ability to identify which technical bets will pay off long-term.",
      "Your exploratory coding sessions often uncover edge cases and requirements that formal planning misses.",
      "You bring a sense of play to programming that keeps the craft alive in an increasingly commoditized field.",
      "Your rapid context-switching, while chaotic, means you cross-pollinate ideas between projects in valuable ways.",
      "You're the rare developer who treats failure as data, not defeat.",
      "Your instinct for when to pivot versus when to persist is better than you give yourself credit for.",
      "You naturally gravitate toward the most impactful problems, even if your path there is winding.",
      "Your enthusiasm for new approaches keeps your team from falling into complacency.",
      "You have a gift for making complex systems feel approachable and fun to work on.",
      "Your messy process produces cleaner insights than most people's structured approaches.",
      "You understand that innovation requires a tolerance for disorder that most organizations desperately need.",
      "Your ability to rapidly discard approaches that aren't working saves more time than careful upfront planning.",
      "You're building a mental library of patterns across dozens of experiments that will compound over your career.",
      "Your AI conversations reveal a mind that thinks in multiple dimensions simultaneously.",
      "You have the rare courage to challenge assumptions that everyone else takes for granted.",
      "Your divergent thinking is exactly what teams need to avoid building the wrong thing perfectly.",
      "When you channel your energy into a single goal, you're genuinely unstoppable.",
      "You understand that the first solution is rarely the best one, and you're willing to keep searching.",
      "Your experimental nature means you've already tried and evaluated approaches others haven't even heard of.",
      "You make the development process feel exciting, which is more valuable than most people realize.",
      "Your code might be chaotic, but your instincts about what to build are remarkably sound.",
      "You have an intuitive understanding of user needs that comes from constantly building and trying things.",
      "Your willingness to take technical risks means you discover opportunities that cautious developers never find.",
      "You bring more creative solutions to a code review than most people bring to a brainstorming session.",
      "Your unconventional approach to problems is exactly what the industry needs more of.",
      "You have a rare ability to make progress in the face of incomplete information.",
      "Your experiments today are laying the groundwork for the best practices of tomorrow.",
      "You're the developer who makes the impossible demo work the night before the presentation.",
      "Your ability to thrive in uncertainty is a skill that becomes more valuable every year.",
      "You don't just think outside the box — you've forgotten the box exists, and that's your greatest strength.",
    ],
  },

  "Silent Architect": {
    archetype: "The Mastermind",
    tagline: "You don't just write code. You design systems.",
    strengths: [
      "Methodical and precise — your code is clean, well-structured, and maintainable",
      "Deep thinker — you understand the 'why' before writing the 'what'",
      "Excellent at designing systems that scale and evolve gracefully",
    ],
    weaknesses: [
      "You over-engineer solutions for problems that don't exist yet",
      "Analysis paralysis — sometimes you think when you should be shipping",
      "You silently judge other people's code but never say anything",
    ],
    habits: [
      "Writes detailed prompts that are longer than the code they produce",
      "Asks the AI to explain its reasoning before accepting suggestions",
      "Has strong opinions about folder structure that they will die on",
      "Reads the entire error message before asking for help (revolutionary)",
    ],
    improvements: [
      "Ship the imperfect version — perfection is the enemy of done",
      "Not every function needs a 5-layer abstraction",
      "Sometimes the quick hack IS the right answer",
    ],
    roasts: [
      "You spent 3 hours designing the perfect folder structure for a todo app.",
      "Your prompts are so detailed they qualify as technical specifications.",
      "You've never pushed to main without running tests three times. We get it, you're responsible.",
      "You've abstractified your code so hard that reading it requires a PhD in category theory.",
      "Your idea of 'moving fast' is only spending one day on the architecture document.",
      "You write design docs for features you'll never build. It's like window shopping but for code.",
      "Your AI agent learned more about software architecture from you than from its training data.",
      "You've never met a problem you couldn't solve with another layer of indirection.",
      "Your code has more interfaces than implementations. The abstractions have abstractions.",
      "You've spent longer choosing between design patterns than it would have taken to just write the code.",
      "Your folder structure has more nesting levels than a Russian doll factory.",
      "You've drawn more architecture diagrams this sprint than you've written lines of code.",
      "Your AI conversations read like a graduate seminar on systems design. For a button component.",
      "You've created a generic, extensible, plugin-based solution for a problem that only has one case.",
      "Your code is so well-organized that finding anything takes three indirection layers and a map.",
      "You've spent 45 minutes explaining to your AI why its perfectly working solution isn't 'architecturally sound'.",
      "Your dependency injection container has more registrations than your app has features.",
      "You've never written a function without first considering how it fits into the broader system ontology.",
      "You treat writing a utility function like you're ratifying an international treaty.",
      "Your type definitions are longer than your business logic. On purpose.",
      "You've refactored working code into a pattern it didn't need just because the pattern exists.",
      "You've rejected an AI suggestion that solved the problem because it wasn't 'idiomatic enough'.",
      "Your code reviews are so thorough they take longer than writing the code from scratch would have.",
      "You have opinions about database schema design that you bring up at parties. You don't get invited to many parties.",
      "You've written a factory for a class that's only instantiated once.",
      "Your config files have their own config files.",
      "You've debated the merits of hexagonal vs. onion architecture for a script that runs once a month.",
      "Your commit messages read like chapters from a software engineering textbook.",
      "You've planned for scale that your app will never reach unless every human on Earth signs up twice.",
      "You treat every code change like it's going to be reviewed by Dijkstra's ghost.",
      "You've created an event-driven system for a feature that receives one event per day.",
      "Your notion of 'rapid prototyping' involves three days of interface design before writing any logic.",
      "You've turned down a working solution because it didn't follow SOLID principles closely enough.",
      "Your monorepo has more workspace configurations than workspaces.",
      "You've spent more time on your ESLint config than most people spend on their entire project.",
      "Your API has versioning, pagination, rate limiting, and caching. It serves one client. You.",
      "You've written abstract base classes for things that will only ever have one subclass.",
      "Your error handling strategy has its own RFC document.",
      "You've created a microservice architecture for a project with one developer. It's you.",
      "You plan for backward compatibility in personal projects that nobody else will ever use.",
      "Your git hooks run more checks than a NASA launch sequence.",
      "You've optimized a function that runs once at startup and takes 2ms.",
      "Your README has a section on architectural decisions that's longer than the actual codebase.",
      "You've migrated databases for a project that doesn't have users yet.",
      "You write middleware for middleware. It's middleware all the way down.",
      "You have a naming convention document. For a solo project. It's twelve pages.",
      "Your tests are so comprehensive they took longer to write than the feature they're testing will ever be used.",
      "You've created a plugin system for an application that will only ever have one plugin.",
      "Your logging strategy has log levels that even your logs don't understand.",
      "You've set up CI/CD pipelines with 47 steps for a project that's still in the planning phase.",
    ],
    compliments: [
      "Your code will still be readable and maintainable five years from now. That's incredibly rare.",
      "You understand that good architecture saves more time than it costs. Most developers learn this too late.",
      "The way you communicate technical decisions is a skill most senior engineers never develop.",
      "Your attention to edge cases and error handling prevents bugs that others wouldn't catch until production.",
      "You're the person who makes everyone else's code better just by being on the team.",
      "Your systems thinking ability is exceptional — you see the whole forest, not just the trees.",
      "Your codebase is one of the few that new developers can onboard to without a week of confusion.",
      "The patterns you establish in a project become the foundation that makes everything else possible.",
      "Your discipline in maintaining clean architecture pays dividends that compound over the entire project lifecycle.",
      "You have a rare ability to anticipate how requirements will evolve, and your code gracefully accommodates that.",
      "Your technical documentation is so clear it could be published as a tutorial.",
      "You bring a level of rigor to software design that elevates the entire engineering culture around you.",
      "The consistency of your code style makes collaboration frictionless for everyone on the team.",
      "Your approach to error handling means your systems fail gracefully when others would crash spectacularly.",
      "You understand that the most expensive code is code that has to be rewritten. Yours rarely does.",
      "Your API designs are intuitive enough that people can use them without reading the documentation.",
      "You have the patience to get the foundations right, which is why your projects age well while others rot.",
      "Your code reviews teach people more about software engineering than most courses do.",
      "You bring architectural thinking to conversations where it's needed but nobody else is providing it.",
      "Your ability to decompose complex systems into clean, testable components is genuinely masterful.",
      "The abstractions you create actually make things simpler, not just more abstract. That's the hard part.",
      "You understand trade-offs at a level that takes most engineers a decade to develop.",
      "Your systems handle edge cases that nobody even thought to test for, because you thought of them first.",
      "Your naming conventions make code self-documenting — readers understand intent without needing comments.",
      "You have the rare combination of seeing both the big picture and the small details simultaneously.",
      "Your refactoring skills are exceptional — you improve code structure without changing behavior, which is an art form.",
      "The technical decisions you make today prevent entire categories of bugs tomorrow.",
      "Your code is the kind that makes other developers say 'I wish I wrote this'.",
      "You bring a calm, methodical approach to problems that keeps teams grounded during crises.",
      "Your understanding of system boundaries and interfaces makes integration work seamless.",
      "You're the architect whose buildings still stand decades later, in a field where most things crumble in months.",
      "Your ability to say 'no' to unnecessary complexity is one of the most valuable skills in engineering.",
      "You design systems that are a pleasure to extend and modify, which is the true mark of good architecture.",
      "Your approach to AI-assisted development — questioning and verifying — produces higher quality output than blind acceptance.",
      "You think about the developer who will maintain this code in two years. That empathy is rare and valuable.",
      "Your technical judgment is trusted because you've earned it through consistently sound decisions.",
      "You understand that simplicity on the other side of complexity is the highest form of engineering.",
      "Your code has a clarity of purpose that makes it almost self-maintaining.",
      "You bring engineering discipline to a field that desperately needs more of it.",
      "Your systems are built to evolve, not just to work today — and that forward-thinking saves enormous effort later.",
      "The way you balance abstraction with pragmatism shows a level of craft that takes years to develop.",
      "You're the reason your team's codebase doesn't have the 'legacy code' problem that plagues most projects.",
      "Your careful approach to dependency management keeps projects healthy long after the initial excitement fades.",
      "You understand that architecture is not about complexity — it's about making the right things easy.",
      "Your code tells a story that any developer can follow, and that narrative quality is genuinely exceptional.",
      "You create the kind of technical environment where other developers do their best work.",
      "Your patience with getting the design right means your team spends less time fighting the codebase.",
      "You have a gift for turning vague requirements into precise, well-structured implementations.",
      "The guardrails you build into your systems prevent entire teams from making costly mistakes.",
      "Your approach to software engineering is one that the industry should study and emulate.",
    ],
  },

  "Rubber Duck Supremacist": {
    archetype: "The Philosopher",
    tagline: "You don't just use AI — you have conversations with it.",
    strengths: [
      "Deep understanding — you don't just copy solutions, you understand them",
      "Excellent at breaking down complex problems into digestible pieces",
      "Naturally curious — you learn faster than most because you ask 'why'",
    ],
    weaknesses: [
      "You ask so many questions you sometimes forget to actually code",
      "Tendency to over-explain problems when a simple example would suffice",
      "You've spent 20 minutes asking about a concept you could have just tried",
    ],
    habits: [
      "Starts every prompt with 'Can you explain...'",
      "Asks follow-up questions to follow-up questions",
      "Uses AI as a thinking partner more than a code generator",
      "Has lengthy philosophical debates about naming conventions",
    ],
    improvements: [
      "Sometimes the fastest way to understand is to just try it",
      "Your AI agent doesn't need the full backstory every time",
      "Set a timer — if you've been asking questions for 15 minutes without coding, just start coding",
    ],
    roasts: [
      "You've asked your AI agent 'but why?' so many times it's having an existential crisis.",
      "Your conversation history looks like a Computer Science lecture series that nobody enrolled in.",
      "You don't have a rubber duck — you have a rubber university.",
      "You've spent more time understanding the solution than it would have taken to write it from scratch.",
      "Your AI agent knows more about your thought process than your therapist does.",
      "You treat every coding task like a Socratic dialogue. Just write the function.",
      "Your prompts have footnotes. FOOTNOTES.",
      "You've never copy-pasted code without first asking for a 3-paragraph explanation of how it works.",
      "Your AI conversation threads are longer than most novels and about as plot-driven.",
      "You've asked 'can you explain that differently?' so many times the AI is running out of metaphors.",
      "Your chat history could be published as 'Introduction to Computer Science: An Oral History'.",
      "You treat your AI like a professor during office hours — except the office hours never end.",
      "You've asked for an ELI5, then an ELI10, then an ELI-PhD. Pick a level.",
      "Your AI agent has explained recursion to you recursively, and you asked it to explain why that's funny.",
      "You've turned a 5-minute bug fix into a 2-hour lecture on the history of error handling.",
      "You asked your AI to explain a one-liner, and the explanation was 47 lines long. You asked for more detail.",
      "Your coding sessions generate more questions than answers. You're running a question deficit.",
      "You've asked 'what are the trade-offs?' about a console.log placement.",
      "Your AI agent has used the phrase 'as I mentioned earlier' more with you than with any other user.",
      "You once asked your AI to explain the difference between two identical approaches. It made something up just to have an answer.",
      "You've turned 'hello world' into a philosophical exploration of what it means to greet a computational environment.",
      "Your conversation history has a table of contents. You added it yourself.",
      "You've asked so many follow-up questions that the AI forgot what the original question was.",
      "You treat Stack Overflow answers like peer-reviewed research — you need to verify every claim independently.",
      "You've spent 30 minutes asking about edge cases for a feature that has three users. All of them are you.",
      "Your AI thinks you're writing a textbook. You're just trying to center a div.",
      "You've asked your AI to compare and contrast five different sorting algorithms for a list of seven items.",
      "Your understanding of the problem is encyclopedic. Your progress on solving it is nonexistent.",
      "You've read the entire MDN article, the spec, and two RFCs before writing a single line of CSS.",
      "You don't just want the answer — you want the answer's origin story, motivations, and character arc.",
      "You've turned your AI into a personal tutor who is never allowed to give you the answer directly.",
      "Your prompt history reads like a graduate thesis defense that never ends.",
      "You once spent an hour understanding a library's internals to use one function that's in the getting started guide.",
      "You've asked 'is there a better way to do this?' about code that was already the best way.",
      "Your AI agent has started preemptively explaining things you haven't asked about yet, just to save time.",
      "You treat every function call like it deserves a Wikipedia article.",
      "You've asked for the 'mental model' behind a for loop. A for loop.",
      "Your development process is: read for 3 hours, ask questions for 2 hours, code for 15 minutes.",
      "You've requested architectural justification for choosing between single quotes and double quotes.",
      "You have more bookmarked documentation tabs than lines of code in your project.",
      "Your AI agent has explained promises to you using seventeen different real-world analogies. You asked for an eighteenth.",
      "You've asked your AI 'what would happen if...' more times than you've asked it to write code.",
      "Your conversation threads have so many tangents they need their own branching strategy.",
      "You once paused a coding session for 40 minutes to understand why null and undefined are different.",
      "You've asked your AI to 'steelman the opposing approach' for a variable naming decision.",
      "Your learning curve looks like an asymptotic function — always approaching but never reaching 'time to code'.",
      "You've debated the philosophical implications of immutability with a language model. For fun.",
      "Your AI suggested you 'just try it and see' and you asked it to explain what empiricism means first.",
      "You treat writing code like writing a dissertation — there's always more research to do.",
      "Your question-to-code ratio would concern any project manager who saw it graphed.",
    ],
    compliments: [
      "Your deep understanding of code means you rarely introduce bugs that others would miss.",
      "You're building genuine expertise, not just stitching together Stack Overflow answers.",
      "The way you use AI as a learning tool rather than a crutch sets you apart from most developers.",
      "Your intellectual curiosity is infectious — you make the people around you better engineers.",
      "You'll be the one who actually understands the system when it breaks at 3am.",
      "Your ability to ask the right questions is more valuable than most people's ability to write code.",
      "When you finally write code, it's informed by a depth of understanding that makes it exceptionally robust.",
      "Your questioning nature means you catch flawed assumptions before they become expensive problems.",
      "You're developing the kind of foundational knowledge that makes senior engineers truly senior.",
      "The mental models you build through questioning will serve you for your entire career.",
      "You're the team member who spots the flaw in the approach during design review, saving weeks of wasted work.",
      "Your curiosity drives you to understand systems at a level where you can innovate, not just maintain.",
      "You use AI in the way it's most powerful — as a thinking partner, not just a code generator.",
      "Your approach produces fewer bugs in production because you understood the solution before implementing it.",
      "You're the developer who can explain complex systems to non-technical stakeholders because you truly understand them.",
      "Your thorough understanding means you write code that handles edge cases others don't even consider.",
      "You have a gift for knowing which questions to ask, which is more important than having answers.",
      "Your deep-dive approach means you're building compound knowledge that accelerates everything you do over time.",
      "The quality of your questions reveals a mind that thinks in systems, not just syntax.",
      "You're developing an intuition for code quality that can't be taught — it has to be discovered through exactly the kind of exploration you do.",
      "Your conversations with AI produce better code than most people's copy-paste-and-pray approach.",
      "You understand the 'why' behind patterns, which means you know when to break the rules appropriately.",
      "Your inquisitive approach to AI creates a feedback loop of understanding that makes you exponentially better over time.",
      "You have the patience to truly learn, which is rarer and more valuable than being fast.",
      "Your ability to decompose complex problems into precise questions is a genuine analytical superpower.",
      "You're the developer who can debug anything because you understand how things work at a fundamental level.",
      "Your questioning process, while slow, produces solutions that are more correct and more maintainable.",
      "You bring a depth of understanding to technical discussions that elevates the entire team's thinking.",
      "The way you synthesize information from multiple explanations shows exceptional analytical ability.",
      "You're building the kind of expertise that makes you the go-to person when nobody else knows the answer.",
      "Your thorough approach to understanding means you make fewer mistakes that matter.",
      "You have the rare skill of knowing what you don't know, which is the beginning of all real expertise.",
      "Your AI conversations aren't wastes of time — they're investments in understanding that pay dividends for years.",
      "You approach programming with the rigor of a scientist, and that produces reliable, trustworthy code.",
      "Your tendency to explore before implementing means your solutions are well-considered, not just functional.",
      "You understand that programming is about modeling reality, and your questions help you model it more accurately.",
      "Your deep knowledge makes you the person who prevents the team from adopting the wrong technology.",
      "You have an exceptional ability to transfer knowledge from one domain to another because you understand fundamentals.",
      "Your code tells people not just what it does, but why it does it that way — because you actually know.",
      "You're the rare developer who reads the documentation, and your code quality shows it.",
      "Your approach to learning through questioning builds a resilience to hype cycles and fads.",
      "You'll be the developer who transitions smoothly as technology changes, because you understand principles, not just tools.",
      "Your philosophical approach to code helps teams make better long-term decisions.",
      "You have the empathy to explain complex concepts to others because you remember what it was like not to understand.",
      "Your commitment to understanding produces code that's correct for the right reasons, not by accident.",
      "You demonstrate that the best developers aren't the fastest typists — they're the deepest thinkers.",
      "Your questioning process documents your reasoning in a way that benefits everyone who reads the conversation later.",
      "You're proof that curiosity is the most important quality a developer can have.",
      "Your deep understanding means your code reviews catch conceptual errors, not just style issues.",
      "The knowledge base you're building through your explorations will make you an irreplaceable team member.",
    ],
  },

  "The Eternal Debugger": {
    archetype: "The Firefighter",
    tagline: "You don't write bugs. You inherit them.",
    strengths: [
      "Unshakable persistence — you will find the bug no matter how long it takes",
      "Deep knowledge of how systems actually break in practice",
      "Excellent diagnostic skills — you can read a stack trace like a novel",
    ],
    weaknesses: [
      "You spend so much time debugging that you forget to write new features",
      "Tendency to go down rabbit holes that turn out to be irrelevant",
      "You fix the symptom before understanding the root cause more often than you'd admit",
    ],
    habits: [
      "First prompt is always 'why is this not working'",
      "Has an intimate relationship with console.log",
      "Adds 'just in case' error handling everywhere",
      "Keeps broken code commented out 'for reference'",
    ],
    improvements: [
      "Write tests BEFORE the code — it's called prevention, not just treatment",
      "Sometimes the bug is in your assumptions, not your code",
      "Take a break when stuck — the answer often comes when you stop looking for it",
    ],
    roasts: [
      "You've debugged more code than you've written. At this point you're not a developer, you're a code coroner.",
      "Your AI agent's most used phrase with you is 'have you tried adding a console.log?'",
      "You've traced so many stack traces that you dream in error messages.",
      "Your git history is just 'fix', 'actually fix', 'for real this time fix', 'okay NOW it's fixed'.",
      "You treat every bug like it's the final boss in a video game. Sometimes it's just a missing semicolon.",
      "You've spent 4 hours debugging a problem that was caused by a typo you made in the first 30 seconds.",
      "Your code works, but nobody knows why — including you.",
      "You've restarted your dev server so many times it has its own frequent flyer miles.",
      "Your console.log collection is so dense it has its own weather system.",
      "You've added so many try-catch blocks your code reads like a safety manual.",
      "You've googled the same error message so many times that Google autocompletes it after one letter.",
      "Your browser's developer tools are open so much they've filed for residency.",
      "You've rage-deleted node_modules so many times npm thinks you're stress testing their CDN.",
      "Your debugging process is: add log, read log, add more logs, lose the original bug in a sea of logs.",
      "You've discovered bugs in libraries you didn't even know your project was using.",
      "You treat 'it works on my machine' as a philosophical statement about the nature of reality.",
      "Your AI agent has started diagnosing your bugs before you finish describing them. It's seen this movie before.",
      "You've written more bug reports than feature specs this quarter. By a factor of ten.",
      "You once fixed a bug that introduced two new bugs. Your net bug count is going in the wrong direction.",
      "Your breakpoint game is so strong that the code spends more time paused than running.",
      "You've become so good at reading stack traces that you've lost the ability to read normal English prose.",
      "Your git stash is full of 'saving this in case the fix breaks something else'.",
      "You've blamed the compiler, the runtime, the OS, the hardware, and the weather before finding your own typo.",
      "Your debugging sessions are so long your AI agent has started charging overtime.",
      "You've set up logging so comprehensive your log files are bigger than your database.",
      "You've fixed the same race condition three times because you keep re-introducing it with new features.",
      "Your IDE's 'find and replace' is just a debugging tool at this point.",
      "You've memorized more error codes than phone numbers.",
      "Your most productive days are the ones where you delete more code than you add.",
      "You've become so paranoid about bugs that you test your tests.",
      "Your code has more defensive checks than a paranoid security guard.",
      "You once followed a bug through seven microservices, two databases, and a message queue. It was a null check.",
      "Your rubber duck has PTSD from all the debugging sessions.",
      "You've spent so much time in the debugger that you think in breakpoints.",
      "Your PR descriptions are just lists of bugs you fixed along the way to the actual feature.",
      "You've created monitoring dashboards for monitoring dashboards.",
      "Your code comments are just warnings to future developers about where the dragons are.",
      "You've asked your AI 'why is this null?' more times than you've said 'good morning' to colleagues.",
      "Your error handling has error handling. It's try-catches all the way down.",
      "You've fixed bugs in production at 3am so many times your coffee maker is on a UPS backup.",
      "You're the only developer who reads release notes specifically to anticipate what they'll break.",
      "Your test environment has more monitoring than most companies' production systems.",
      "You've built more workarounds than features. Your codebase is basically a museum of patches.",
      "You once spent a full day tracking a bug that only manifested on the second Tuesday of months with 31 days.",
      "Your debugging strategy includes techniques that haven't been documented because you invented them in desperation.",
      "You've added 'THIS IS NOT A BUG' comments to code that looks like a bug but is actually intentional.",
      "Your AI agent has started guessing your next question is 'why is this still broken?'",
      "You've bisected your git history so many times you could do it in your sleep.",
      "Your relationship with undefined is more complicated than any romantic relationship you've ever had.",
      "You treat console.log the way other developers treat meditation — it's how you find inner peace.",
    ],
    compliments: [
      "Your ability to stay calm and methodical when everything is on fire is genuinely admirable.",
      "You have an instinct for finding bugs that automated testing would miss.",
      "Your persistence is your superpower — most developers would have given up where you kept going.",
      "You understand production systems in a way that developers who only write greenfield code never will.",
      "Your debugging skills make you the most valuable person in the room during an incident.",
      "You've probably prevented more outages than anyone will ever know about.",
      "Your deep familiarity with failure modes makes you an invaluable asset during system design.",
      "The patience you bring to debugging is a rare and genuinely valuable trait in this industry.",
      "You have an encyclopedic knowledge of error patterns that saves your team countless hours.",
      "Your ability to reproduce edge-case bugs that others dismiss as 'flaky' is genuinely impressive.",
      "You make systems more reliable just by being involved — your paranoia about failure is a feature, not a bug.",
      "Your diagnostic skills are transferable to any technology, any language, any system. That's true expertise.",
      "You understand that the hardest part of software isn't writing it — it's making it work. And you're the best at that.",
      "Your experience with failure gives you a perspective on resilience that greenfield developers lack entirely.",
      "You're the developer who writes the post-mortem that actually prevents the next incident.",
      "Your debugging sessions, while long, produce solutions that stick. You fix things for real.",
      "You have a mental model of how systems break that's worth more than any architecture document.",
      "Your attention to error handling saves your users from experiencing the bugs you've become expert at finding.",
      "You bring a scientific rigor to debugging that turns chaos into understanding.",
      "Your knowledge of system internals is the kind that can't be taught — it's earned through battle.",
      "When a production incident happens, you're the person everyone trusts to figure it out. That trust is earned.",
      "Your ability to stay focused during long debugging sessions shows a mental discipline most people lack.",
      "You understand that software quality isn't about writing perfect code — it's about finding and fixing imperfection.",
      "Your bug reports are so thorough they could be submitted as academic case studies.",
      "The monitoring and alerting systems you set up have saved your team from disasters they never even knew about.",
      "You have a rare talent for turning vague bug reports into reproducible test cases.",
      "Your experience debugging complex systems gives you an intuition that no amount of reading can provide.",
      "You're the reason your team can sleep at night — because you've already found and fixed the things that would have woken them up.",
      "Your ability to trace causality through complex systems is a form of detective work that few people master.",
      "You make other developers write better code because they know you'll find their bugs. That's a positive force.",
      "Your knowledge of how things fail informs how you build things, making your new code remarkably robust.",
      "You're the developer who turns a system outage into a learning opportunity that makes the whole team better.",
      "Your systematic approach to debugging could be taught as a masterclass in logical reasoning.",
      "You understand that every bug is a gap in understanding, and your drive to close those gaps makes you exceptional.",
      "Your ability to hold complex system state in your head while debugging is a genuine cognitive feat.",
      "You bring a level of thoroughness to problem-solving that prevents the same issue from ever occurring twice.",
      "Your debugging experience has given you an unusually accurate mental model of how software actually behaves.",
      "You're proof that the ability to fix things is just as valuable as the ability to build them.",
      "Your error handling isn't paranoia — it's professionalism. And the code you protect is better for it.",
      "You have the humility to consider that the bug might be in your own code, which makes you find it faster.",
      "Your persistence through difficult bugs demonstrates a grit that translates to everything you do.",
      "You understand the entire stack in a way that specialists in one layer simply can't.",
      "The observability you build into systems is a gift to every developer who will ever work on them after you.",
      "Your ability to work under pressure during incidents is the result of genuine expertise, not just adrenaline.",
      "You make the systems you touch measurably more reliable, and that impact compounds over time.",
      "Your debugging stories are the ones the team retells for years because they reveal how deeply you understand the code.",
      "You have the rare ability to see patterns across seemingly unrelated bugs and find their common root cause.",
      "Your empathy for end users — born from fixing the bugs they encounter — makes you a better developer overall.",
      "The resilience you build into code comes from having seen every way things can go wrong, and that knowledge is priceless.",
      "You understand that reliability is a feature, not an afterthought, and your code reflects that understanding.",
    ],
  },

  "10x Goblin": {
    archetype: "The Machine",
    tagline: "You don't waste time. Time wastes you.",
    strengths: [
      "Extraordinary output — you ship features at a pace that seems impossible",
      "Ruthless prioritization — you know exactly what matters and what doesn't",
      "AI power user — you've turned AI into an extension of your own thinking",
    ],
    weaknesses: [
      "You move so fast that code quality occasionally takes a back seat",
      "Not everything needs to be optimized for speed — some things need care",
      "You rely heavily on AI, which could be a problem if it hallucinates",
    ],
    habits: [
      "Sends multiple prompts before the AI finishes responding",
      "Has the shortest average prompt length in recorded history",
      "Uses AI for literally everything, including writing commit messages",
      "Context-switches between projects like a CPU scheduler",
    ],
    improvements: [
      "Slow down occasionally — speed kills (code quality)",
      "Read the AI's response before sending the next prompt",
      "Invest 10% of your time in code review — future you is begging you",
    ],
    roasts: [
      "You type faster than your AI can respond. At this point, who's assisting whom?",
      "Your AI agent needs therapy from the sheer volume of requests you send it.",
      "You ship code so fast that QA can't even find it before you've already refactored it.",
      "You've automated yourself into a corner where you can't function without AI. Congratulations?",
      "Your commit frequency is so high it looks like a DDoS attack on the repository.",
      "You treat your AI like an unpaid intern — short commands, no context, expect miracles.",
      "Your idea of 'code review' is waiting 3 seconds to see if it compiles.",
      "You've shipped more code this month than some teams ship in a quarter. Your tech debt agrees.",
      "You've accepted AI suggestions so fast you didn't notice one of them was in a different programming language.",
      "Your prompt history is just single words: 'fix', 'faster', 'next', 'ship', 'deploy'.",
      "You treat rate limits like personal challenges.",
      "Your AI agent's response time is the longest relationship you've committed to.",
      "You've pushed to production before your CI pipeline even started running.",
      "Your keyboard has a lower life expectancy than your average branch.",
      "You generate more code per hour than some teams generate per sprint. Nobody can review it that fast.",
      "You've used AI to write a script to automate your AI prompts. We're in recursion territory.",
      "Your git activity graph doesn't have gaps. Not even on holidays. Not even at 4am.",
      "You merge your own PRs faster than GitHub can send the notification email.",
      "Your code completion suggestions have code completion suggestions.",
      "You've broken the build so many times this week the CI server has a support group.",
      "You've written more boilerplate removal scripts than you've written boilerplate. Net negative boilerplate developer.",
      "Your development environment has so many shortcuts that your keyboard just shows question marks.",
      "You send 'do this' to your AI and expect it to read your mind. Somehow, it often does.",
      "Your standup updates are longer than everyone else's combined because you actually did that many things.",
      "You've opened, fixed, and closed an issue before anyone else noticed it existed.",
      "You use AI tokens like they're going out of style. Your monthly usage graph looks exponential.",
      "Your terminal has more aliases than a witness protection database.",
      "You've deployed 14 times today. It's not even lunch yet.",
      "You read documentation at the speed of scrolling. Which is to say, you don't read documentation.",
      "Your feature branches live for an average of 47 minutes before being merged. Some butterflies live longer.",
      "You've automated your morning routine so thoroughly that your laptop is productive before you're awake.",
      "You treat every AI response like a pull cord — grab the code, yank it into your project, keep moving.",
      "Your typing speed is measured in commits per minute.",
      "You've filed and resolved bugs faster than Jira can update the sprint board.",
      "Your development process is a blur that can only be captured with a high-speed camera.",
      "You've finished the sprint backlog by Tuesday. The sprint started Monday.",
      "Your code has 'TODO' comments from last week that you haven't looked at because you've already moved three projects ahead.",
      "You treat token limits like speed bumps — annoying but ultimately ignorable.",
      "Your git log looks like it was generated by a machine. Because half of it was.",
      "You've optimized your workflow so much that your bottleneck is now your internet speed.",
      "You send your AI three prompts in the time it takes to respond to one. It's not a conversation, it's a barrage.",
      "Your 'done' definition is 'it compiles and the tests I didn't write would probably pass'.",
      "You've shipped features that your product manager hasn't even added to the roadmap yet.",
      "You go through AI models the way musicians go through guitar picks.",
      "Your co-workers think you're three people working in shifts.",
      "You've hit API rate limits on services that didn't think rate limiting was necessary.",
      "Your browser has so many tabs open that they've become single-pixel slivers of existential dread.",
      "You treat lunch as an unnecessary blocking operation in your daily pipeline.",
      "Your output is so high that your performance review is just a CSV file.",
      "You've created more repositories this month than some organizations create in a year.",
    ],
    compliments: [
      "Your productivity is genuinely awe-inspiring. You output more than most small teams.",
      "You've mastered the art of using AI as a force multiplier — most people are still figuring that out.",
      "Your ability to context-switch and maintain velocity across projects is a rare talent.",
      "You understand that shipping imperfect code today is often better than perfect code next month.",
      "You're proof that one developer with the right tools can move mountains.",
      "Your speed doesn't come from shortcuts — it comes from experience and pattern recognition.",
      "You have an incredible ability to separate signal from noise and focus on what matters most.",
      "Your output creates momentum for entire teams — when you ship, it unblocks everyone around you.",
      "You've developed an intuition for the minimum viable solution that solves the actual problem.",
      "Your efficiency with AI tools is a skill that will only become more valuable as the industry evolves.",
      "You understand leverage better than most engineers — you amplify your impact through smart tool use.",
      "Your ability to maintain quality at high speed is rarer than people think.",
      "You have a talent for identifying the 20% of work that delivers 80% of the value.",
      "Your velocity gives your team the ability to iterate faster, which leads to better products.",
      "You bring an urgency to development that keeps projects from stalling in endless deliberation.",
      "Your instinct for 'good enough' isn't laziness — it's a deep understanding of diminishing returns.",
      "You've turned AI pair programming into a genuine competitive advantage. That's a real skill.",
      "Your ability to rapidly prototype and validate ideas saves resources that would otherwise be wasted.",
      "You demonstrate that throughput and thoughtfulness aren't mutually exclusive.",
      "Your comfort with shipping and iterating means you get real user feedback while others are still in design.",
      "You make the development cycle shorter, which means bugs are found sooner and fixes arrive faster.",
      "Your approach to development is a masterclass in prioritization and execution.",
      "You have an exceptional ability to find the critical path through complex projects.",
      "Your speed creates optionality — you can explore more approaches and pick the best one.",
      "You're the rare developer who doesn't just talk about agile principles but actually lives them.",
      "Your tool fluency — AI, editors, CLIs — is the result of deliberate optimization that most people neglect.",
      "You understand that in a fast-moving market, speed of execution is itself a competitive advantage.",
      "Your ability to maintain multiple contexts simultaneously shows exceptional cognitive capacity.",
      "You bring a results-oriented mindset that keeps teams focused on outcomes rather than process.",
      "Your quick iterations produce more learning per unit of time than careful, slow approaches.",
      "You have a gift for automation that multiplies your impact far beyond your individual contribution.",
      "Your development style proves that you can be both fast and thoughtful about what you build.",
      "You create a culture of shipping that raises the bar for everyone on the team.",
      "Your ability to quickly assess AI output and integrate it effectively is a skill most developers haven't developed.",
      "You understand that code is a means to an end, and your focus on the end makes you exceptionally effective.",
      "Your pace pushes the boundaries of what people think is possible for a single developer.",
      "You have an instinct for when to invest in quality and when speed is the right trade-off.",
      "Your efficiency inspires other developers to optimize their own workflows.",
      "You demonstrate that high output and sustainability can coexist when you work smart.",
      "Your ability to ship consistently is one of the most reliable indicators of engineering effectiveness.",
      "You turn AI from a novelty into a genuine productivity system. That's an engineering achievement in itself.",
      "Your output speaks for itself — and it says more than most people's planning documents.",
      "You have the rare ability to make progress every single day, regardless of blockers.",
      "Your workflow optimizations compound over time, making you exponentially more productive.",
      "You're the person teams want on a deadline because you deliver. Consistently. Without drama.",
      "Your approach to AI-assisted development is what the industry will look like in five years. You're already there.",
      "You understand that perfection is the enemy of progress, and you consistently choose progress.",
      "Your ability to scope work down to its essence saves entire teams from building the wrong thing.",
      "You bring a startup mentality to everything you do — move fast, learn fast, adapt fast.",
      "Your combination of speed and judgment makes you one of the most effective developers in any room you're in.",
    ],
  },

  "Copy-Paste Sorcerer": {
    archetype: "The Builder",
    tagline: "Why write from scratch when someone already solved this?",
    strengths: [
      "Incredible efficiency — you don't reinvent wheels",
      "Broad knowledge of existing tools, libraries, and patterns",
      "Fast bootstrapper — you can go from zero to working prototype faster than anyone",
    ],
    weaknesses: [
      "You scaffold more projects than you finish",
      "Sometimes the boilerplate you copy comes with bugs you don't understand",
      "Your code reads like a mixtape — technically works, but the transitions are rough",
    ],
    habits: [
      "Starts every project with 'generate a boilerplate for...'",
      "Has a personal template for everything",
      "Asks AI to scaffold before understanding the requirements",
      "npm install is their love language",
    ],
    improvements: [
      "Understand the boilerplate before building on top of it",
      "Sometimes less dependencies is more",
      "Try building one thing from scratch — you'll learn more than any template can teach",
    ],
    roasts: [
      "Your node_modules folder has more code than the rest of your project combined.",
      "You've scaffolded more projects this month than a construction company.",
      "Your idea of 'writing code' is choosing which template to copy from.",
      "You have a dependency for everything. If there was an npm package for breathing, you'd install it.",
      "Your AI agent is basically a boilerplate dispenser at this point.",
      "You've never met a problem you couldn't solve by adding another dependency.",
      "Your package.json has more entries than your actual source code has lines.",
      "You don't have imposter syndrome — your code does.",
      "Your project is 90% generated code and 10% glue holding generated code together.",
      "You've npm installed so many packages that your hard drive filed a noise complaint.",
      "You treat 'npx create-' as the first four words of every project you'll ever start.",
      "Your codebase is a museum of templates from tutorials you followed halfway.",
      "You've copied code from Stack Overflow so often it should appear as a co-author on your commits.",
      "Your AI agent has generated more of your codebase than you have. You're the minority contributor on your own project.",
      "You've installed a package to left-pad strings. In 2026.",
      "Your import statements take up more screen space than your actual functions.",
      "You've scaffolded a full-stack app with authentication, payments, and a CMS for a project that shows 'Hello World'.",
      "Your dependency tree is more complex than your application logic.",
      "You've never read a library's source code. You just assume it works. Bold strategy.",
      "You treat 'npm audit' warnings like spam emails — acknowledge and ignore.",
      "Your project has more configuration files than source files.",
      "You've asked your AI to 'make this work' more times than you've asked it to 'explain how this works'.",
      "Your git repo is 95% initial commit generated by a scaffolding tool and 5% your actual work.",
      "You've started more projects with 'npx create-next-app' than you've finished with 'npm run build'.",
      "Your development process is: Google it, copy it, paste it, ship it, forget it.",
      "You treat packages like Pokemon — gotta install 'em all.",
      "Your code has so many third-party integrations it's basically a UN assembly.",
      "You've spent more time configuring webpack than actually understanding what it does.",
      "Your lock file diff is always the largest file in every pull request.",
      "You've copied a solution from your own previous project that was itself copied from another project. It's copies all the way down.",
      "Your AI agent suggested you write something from scratch once. You asked it for a template instead.",
      "You measure project progress by how many packages you've installed, not features you've built.",
      "Your node_modules has achieved sentience and is now managing its own dependencies.",
      "You've added a utility library for a single function you could have written in three lines.",
      "Your build time is longer than your development time because of all the dependencies being compiled.",
      "You've migrated between boilerplate templates more times than you've written original code.",
      "Your AI conversations are just 'scaffold this', 'generate that', 'template for the other thing'.",
      "You treat 'npm outdated' as a daily horror show that you watch but never act on.",
      "Your project's bus factor isn't about developers — it's about which packages get deprecated.",
      "You've forked more repos than you've started from scratch. Your GitHub is a hall of mirrors.",
      "Your code review feedback is always 'there's probably a library for this'.",
      "You've tried to install a dependency that turned out to be malware. Twice.",
      "Your project requires Node 18, Python 3.11, Ruby 3.2, and Go 1.21 because different templates needed different runtimes.",
      "You've never deleted a dependency. Your package.json is append-only.",
      "Your development approach is Ctrl+C, Ctrl+V, Ctrl+S, and pray.",
      "You have starter templates for your starter templates.",
      "Your Docker image is 4GB because you included every dependency from every template you considered.",
      "You've spent more time resolving dependency conflicts than writing business logic.",
      "You treat every new project like a buffet — take everything, figure out what you need later.",
      "Your portfolio is technically impressive until someone asks you to explain how any of it works.",
    ],
    compliments: [
      "Your ability to quickly prototype and validate ideas saves enormous amounts of time and resources.",
      "You understand that leveraging existing solutions is a sign of wisdom, not laziness.",
      "Your breadth of knowledge across tools and libraries is genuinely impressive.",
      "You're often the fastest person to get something working — and that matters more than people think.",
      "Your pragmatism is underrated — you solve real problems while others are still debating the approach.",
      "You know the ecosystem better than most — that knowledge compounds over time.",
      "Your ability to evaluate and select the right tool for the job is a skill that saves teams weeks of wrong choices.",
      "You understand that standing on the shoulders of giants is how all progress works.",
      "Your speed to a working prototype gives stakeholders something tangible to react to, which improves outcomes.",
      "You have an exceptional talent for integration — making disparate pieces work together is harder than it looks.",
      "Your awareness of what already exists prevents your team from wasting time solving solved problems.",
      "You understand the build-vs-buy decision better than most engineers, and you usually make the right call.",
      "Your ability to rapidly assemble working systems from existing components is genuinely valuable.",
      "You bring a practical, results-oriented approach that keeps projects grounded in reality.",
      "Your knowledge of the package ecosystem means you can evaluate options faster than anyone on the team.",
      "You're the person who can go from idea to working demo in a day, and that ability is incredibly valuable.",
      "Your comfort with using existing solutions means you deliver faster without the risk of untested custom code.",
      "You have an eye for quality libraries and tools that saves your team from making bad dependency choices.",
      "Your scaffolding skills mean your projects have solid foundations from day one.",
      "You understand that originality in coding isn't about writing everything from scratch — it's about solving problems creatively.",
      "Your ability to learn new tools quickly makes you adaptable in a way that deeply specialized developers aren't.",
      "You bring a builder's mindset — you're focused on what you're making, not how every individual piece works.",
      "Your awareness of existing solutions means you rarely waste time solving a problem that's already been solved well.",
      "You have an intuitive sense for which templates and tools will scale and which will become dead ends.",
      "Your integration skills are genuinely difficult to develop — knowing how pieces fit together is its own expertise.",
      "You make teams more efficient by introducing them to tools and libraries they didn't know existed.",
      "Your approach to development mirrors how the best products are built — leverage the ecosystem, focus on your unique value.",
      "You understand that every line of code is a liability, and using well-maintained libraries reduces that liability.",
      "Your speed to market gives your team a competitive advantage that's hard to replicate.",
      "You have a curator's eye — you don't just find solutions, you find the right solutions for the specific context.",
      "Your ability to assemble complex systems quickly means your team can experiment with approaches others can't afford to try.",
      "You understand that the NPM ecosystem, while imperfect, represents collective human effort that would be foolish to ignore.",
      "Your pragmatic approach to code reuse is exactly what most teams need but few practice well.",
      "You bring projects to life faster than anyone, and that initial momentum is often what determines project success.",
      "Your experience with diverse tools and frameworks gives you a perspective that pure specialists simply don't have.",
      "You're the person who saves a team from spending six months building what an existing library does in six lines.",
      "Your pattern recognition for 'this has been solved before' is a genuine productivity superpower.",
      "You understand that modern software development is about composition, and you're a master composer.",
      "Your ability to evaluate the trade-offs of different libraries shows a practical wisdom that's hard to teach.",
      "You demonstrate that being efficient and being skilled are not mutually exclusive.",
      "Your project bootstrap time is the envy of every developer who's spent weeks on initial setup.",
      "You have a gift for seeing which pieces of existing code can be adapted to new contexts.",
      "Your wide exposure to different codebases gives you a breadth of patterns that purely original coders miss.",
      "You understand that developer productivity is about solving the right problems, not solving all problems from scratch.",
      "Your scaffolding approach means your projects start with established best practices built in.",
      "You bridge the gap between what the ecosystem offers and what your project needs, and that bridge-building is real engineering.",
      "Your ability to quickly evaluate package quality, maintenance status, and community support saves your team from bad choices.",
      "You understand that reinventing the wheel is only valuable if you need a fundamentally different wheel.",
      "Your development speed enables rapid iteration cycles that produce better end products.",
      "You're proof that knowing what to use is just as important as knowing how to build it.",
    ],
  },

  "The Micromanager": {
    archetype: "The Perfectionist",
    tagline: "Every pixel matters. Every variable name matters. Everything matters.",
    strengths: [
      "Exceptional attention to detail — your code is polished and precise",
      "High-quality output — when you ship something, it's done right",
      "Great at providing context — your prompts leave no room for ambiguity",
    ],
    weaknesses: [
      "You spend 30 minutes wordsmithing a prompt that could have been 2 sentences",
      "Perfectionism slows you down — sometimes 'good enough' is good enough",
      "You over-specify requirements to AI, leaving no room for creative solutions",
    ],
    habits: [
      "Writes prompts longer than the code they produce",
      "Reviews AI output line by line before accepting anything",
      "Asks for multiple revisions of the same function",
      "Has strong opinions about trailing commas",
    ],
    improvements: [
      "Trust the AI a little more — it's surprisingly good at inferring context",
      "Set a time limit on prompt crafting — diminishing returns are real",
      "Accept that 'done' is a feature",
    ],
    roasts: [
      "Your prompts have more requirements than a NASA mission briefing.",
      "You've spent more time editing your AI's output than it spent generating it.",
      "Your code review comments are longer than the code itself.",
      "You asked the AI to rewrite the same function 7 times because the variable name wasn't 'expressive enough'.",
      "Your AI agent has learned to pre-emptively apologize for not meeting your standards.",
      "You treat code like a legal document — every character must be accounted for and justified.",
      "You've rejected perfectly working code because the indentation was wrong.",
      "Your Definition of Done is longer than most people's entire project spec.",
      "You've nitpicked a semicolon placement in a language that doesn't require semicolons.",
      "Your AI agent has learned to include 'I can revise this if needed' after every response. It's always needed.",
      "You spent 20 minutes choosing between 'getData' and 'fetchData'. The API doesn't exist yet.",
      "Your linting rules are so strict that valid code fails your checks on philosophical grounds.",
      "You've requested changes on a PR that was already approved by three other reviewers.",
      "You once blocked a deployment because a comment had a period instead of an exclamation mark.",
      "Your AI conversations look like contract negotiations — every detail must be explicitly agreed upon.",
      "You have opinions about line length limits that you've defended more passionately than your salary.",
      "Your code formatting preferences document is version-controlled and on its fifteenth revision.",
      "You've spent longer crafting the perfect prompt than it would have taken to write the code yourself.",
      "Your AI agent sees your name and immediately increases its response detail by 400%.",
      "You treat 'any' types like biohazards. To be fair, you might be right about that one.",
      "You've rewritten code the AI gave you to match your preferred syntax style. It was functionally identical.",
      "Your ESLint config is so customized it qualifies as its own programming language.",
      "You review AI-generated code like it's a thesis defense. Every line must justify its existence.",
      "You've spent an hour deciding between a map and a reduce. The array had two elements.",
      "You once asked your AI to 'make this more elegant' without any other specification. Four revisions later, neither of you knew what elegant meant anymore.",
      "Your commit messages are longer than the diffs they describe.",
      "You've filed style issues as 'critical bugs' and nobody was surprised.",
      "Your Prettier config disagrees with your ESLint config, and you've spent a week resolving their differences.",
      "You've created a PR template that takes longer to fill out than the actual code change.",
      "Your code comments explain not just what the code does, but what it considered doing and why it chose not to.",
      "You've asked your AI for the 'optimal' solution and then rejected it for not being optimal enough.",
      "Your type definitions are so precise they're basically a parallel implementation of the business logic.",
      "You've spent more time perfecting error messages than most people spend on their entire error handling.",
      "You requested a variable be renamed in a file that was about to be deleted.",
      "Your branch names are so descriptive they hit the filesystem character limit.",
      "You've asked your AI to 'reconsider the architectural implications' of a CSS color change.",
      "Your TypeScript strict mode settings have strict mode settings.",
      "You've opened a follow-up PR to fix a typo in a comment that nobody would ever read.",
      "Your test names are complete sentences with proper grammar and punctuation. We're not complaining, but also... why.",
      "You've rolled back a deployment because the logging format changed slightly.",
      "You once spent 45 minutes deciding on the order of CSS properties. Alphabetical won. Then you reconsidered.",
      "Your code has more inline documentation than a government regulation.",
      "You've asked your AI to regenerate an entire component because one prop name was 'misleading'.",
      "Your IDE has so many custom rules that it highlights more warnings than a nuclear control room.",
      "You've blocked a merge because the tests passed 'too quickly' and that was 'suspicious'.",
      "Your AI has started prefacing every response with the exact specifications you'll care about, just to save revision rounds.",
      "You treat each pull request like it's going to be exhibited in a museum of software craftsmanship.",
      "Your git diff reviews include checking whitespace changes that are invisible to the naked eye.",
      "You've sent back AI-generated code because the blank lines between functions weren't consistent.",
      "Your standards are so high that your own code from last month doesn't meet them.",
    ],
    compliments: [
      "Your code quality sets the standard for your entire team. People learn from your example.",
      "Your attention to detail catches bugs that would cost thousands in production.",
      "The care you put into your prompts results in significantly better AI output than most people get.",
      "Your code reviews, while thorough, genuinely make the codebase better.",
      "You understand that quality is not a phase — it's a practice. And you practice it every day.",
      "When your code ships, it stays shipped. No hotfixes, no rollbacks. That's the dream.",
      "Your meticulousness creates a codebase that's a pleasure to work in, not a chore.",
      "Your high standards raise the bar for everyone on the team, making the whole codebase better.",
      "The time you invest in getting things right pays dividends in reduced maintenance burden.",
      "Your code is the kind that other developers enjoy reading — and that's one of the highest compliments in this craft.",
      "Your thorough approach to AI prompting consistently produces higher quality output than others get from the same tools.",
      "You understand that attention to detail is what separates professional software from amateur software.",
      "Your refusal to accept 'good enough' is what produces genuinely excellent software.",
      "The consistency you bring to codebases reduces cognitive load for every developer who touches the project after you.",
      "Your careful code reviews have prevented bugs that no automated tool would have caught.",
      "You create code that's not just functional but genuinely well-crafted, and that craftsmanship matters.",
      "Your naming conventions make code self-documenting — new developers can understand your code without a guide.",
      "The quality of your error messages shows a level of care for end users that most developers don't have.",
      "Your perfectionism, while sometimes slow, produces results that stand the test of time.",
      "You set an example that silently teaches everyone around you what good code looks like.",
      "Your insistence on clear, precise code prevents entire categories of misunderstandings between team members.",
      "Your code reviews are the most effective teaching tool on your team, whether you realize it or not.",
      "You understand that technical polish is not vanity — it's a form of communication and respect for future maintainers.",
      "Your precise specifications help AI tools produce their best work, which makes you more effective than you think.",
      "The quality bar you set is exactly what separates products that survive from products that accumulate debt and die.",
      "Your attention to naming, structure, and organization makes your codebases navigable and intuitive.",
      "You catch the small issues that, left unchecked, compound into large, expensive problems over time.",
      "Your thoroughness in testing means your features work correctly in edge cases that others never even consider.",
      "The standard you hold yourself to is higher than most companies hold their entire engineering team.",
      "Your code quality means fewer support tickets, fewer incidents, and fewer late-night emergency fixes.",
      "You understand that in software, the details aren't just details — they are the design.",
      "Your careful approach to dependency management keeps projects healthy when others accumulate rot.",
      "Your consistent formatting and style make pair programming and code collaboration significantly easier.",
      "You bring a level of professionalism to code that many senior engineers never achieve.",
      "Your thorough documentation of decisions means the team never has to re-debate settled questions.",
      "Your code passes linting on the first try more often than anyone else's. That's not luck — it's discipline.",
      "Your insistence on clear error handling means users get meaningful feedback instead of cryptic failures.",
      "You create the kind of codebase where bugs are easy to find because everything is clear and well-organized.",
      "Your meticulous approach to testing gives the team confidence to refactor and improve without fear.",
      "You understand that clean code isn't just about aesthetics — it's about reducing the cost of change.",
      "Your high standards make you the person teams want reviewing their code before it goes to production.",
      "Your commitment to quality is an investment in the long-term health of every project you touch.",
      "The consistency of your work creates a reliability that stakeholders learn to trust and depend on.",
      "Your precision with AI tools extracts more value from them than other developers who use the same tools carelessly.",
      "You prove that taking the time to do things right is faster in the long run than doing them twice.",
      "Your eye for code quality extends beyond syntax to architecture, patterns, and user experience.",
      "You bring the same level of care to test code as to production code, and that makes your tests actually valuable.",
      "Your perfectionism, channeled well, produces software that users and developers alike appreciate.",
      "The codebases you work on have noticeably fewer 'why is this like this?' moments for new developers.",
      "Your commitment to quality is the bedrock that allows teams to build with confidence.",
    ],
  },

  "LGTM Speedrunner": {
    archetype: "The Pragmatist",
    tagline: "If it works, ship it. If it doesn't, fix it in prod.",
    strengths: [
      "Bias toward action — you get things done while others are still planning",
      "Practical mindset — you focus on outcomes, not process",
      "Low friction — you don't let perfect be the enemy of good",
    ],
    weaknesses: [
      "Your 'fix it later' list is growing faster than your feature list",
      "Code reviews are not just a formality — they actually catch bugs",
      "Moving fast is only valuable if you're moving in the right direction",
    ],
    habits: [
      "Responds to every AI suggestion with 'yes, do it'",
      "Merges PRs faster than anyone can review them",
      "Has never read the 'are you sure?' dialog",
      "Treats error handling as 'TODO: handle errors'",
    ],
    improvements: [
      "Slow down for the critical paths — not everything can be a happy path",
      "Write one test. Just one. See how it feels.",
      "Read the AI's output before accepting it — it might be hallucinating",
    ],
    roasts: [
      "Your code review process is: open PR, scroll to bottom, click 'LGTM'. Speed record: 4 seconds.",
      "You've deployed to production more times today than most people have committed code.",
      "Your approach to error handling is 'catch everything, log nothing, hope for the best'.",
      "You move so fast you make Agile look like Waterfall.",
      "Your 'tech debt' could qualify for its own line item in the company's financial statements.",
      "You treat 'fix it later' like a promise to a future version of yourself that will never exist.",
      "Your tests are just assertions that true equals true. At least they pass.",
      "You've approved more PRs unread than most developers have opened.",
      "You've clicked 'Accept all suggestions' so many times your mouse button is worn flat.",
      "Your rollback game is stronger than your testing game. Way stronger.",
      "You treat staging environments like conspiracy theories — you've heard of them but don't believe in them.",
      "Your deployment pipeline has more rollbacks than a VHS tape in 1995.",
      "You once approved a PR that added a dependency on a package that had been deprecated for two years.",
      "Your idea of a smoke test is 'does the page load without a white screen? Ship it.'",
      "You've shipped console.log('here') to production so many times it's basically a feature.",
      "Your 'testing in production' approach has given your SRE team a permanent eye twitch.",
      "You respond to AI suggestions like someone speed-clicking through Terms of Service.",
      "Your code has more TODO comments than actual implementation comments. The TODOs are the comments.",
      "You've merged your own PR within 30 seconds of opening it. Self-approval is a lifestyle.",
      "Your feature flags are just 'if true' statements you'll 'configure properly later'.",
      "You've never once read the 'breaking changes' section of a changelog before upgrading.",
      "Your approach to code review is ctrl+end, type 'lgtm', submit. You've got it down to muscle memory.",
      "Your AI agent has learned to not explain anything because you're just going to accept whatever it says anyway.",
      "You treat the 'are you sure you want to force push?' dialog like a personal challenge.",
      "Your git log is a speedrun any% category and you're going for the world record.",
      "You've deployed on a Friday at 4:55pm and felt nothing. No fear. No regret. Nothing.",
      "Your 'minimum viable product' would terrify most QA engineers.",
      "You've responded 'LGTM' to a PR that was actually a cry for help in the description.",
      "Your CI pipeline is optional in the same way that brakes on a car are 'optional'.",
      "You've fixed a bug by catching the exception and doing literally nothing with it. Problem solved?",
      "Your approach to database migrations is 'just run it and see what happens'. In production.",
      "You've spent less time on your last ten code reviews combined than most people spend on one.",
      "Your test coverage is a number you've never checked and a concept you've chosen not to engage with.",
      "You've approved PRs from bots without reading them. Even the bots were surprised.",
      "Your idea of 'monitoring' is waiting for a customer to email you that something is broken.",
      "You treat warnings like decorative suggestions from a compiler that's being overly cautious.",
      "Your approach to documentation is 'the code IS the documentation'. The code is not documented either.",
      "You've shipped a migration that dropped a column you later needed. The rollback plan was 'panic'.",
      "Your sprint velocity is legendary. Your bug count is also legendary. Correlation unclear.",
      "You once auto-merged 15 Dependabot PRs at once without reading a single one. On a Friday.",
      "Your code has a 'works on my machine' success rate of 100% and a 'works anywhere else' rate of 60%.",
      "You've closed issues as 'won't fix' faster than they were opened.",
      "Your debugging strategy is to deploy a new version and see if the bug goes away on its own.",
      "You treat code linting errors as a difference of opinion between you and the linter. You always win.",
      "Your notion of backward compatibility is 'tell users to refresh their cache'.",
      "You've written entire features without once running the application locally.",
      "Your PR description says 'no changes needed' on a 500-line diff.",
      "You've copy-pasted your AI's response directly into production code without even reading it. It worked. Somehow.",
      "Your error boundaries are more like error suggestions.",
      "You've completed more deployments today than code reviews in your entire career.",
    ],
    compliments: [
      "Your bias toward action is genuinely valuable — in a world of over-planners, you actually get things done.",
      "You understand that a shipped feature is worth more than a perfect branch that never merges.",
      "Your pragmatism keeps projects moving when everyone else is stuck in analysis paralysis.",
      "You have a rare ability to focus on what matters and cut through the noise.",
      "Your speed creates momentum that lifts entire teams.",
      "You understand something that many engineers don't: done is a feature.",
      "Your ability to make quick decisions under uncertainty is a leadership quality that's genuinely rare.",
      "You keep teams honest about what actually matters versus what's just engineering vanity.",
      "Your instinct for 'ship and iterate' produces better products than 'plan and perfect' in most cases.",
      "You have an intuitive sense for when something is 'good enough' that saves enormous amounts of time.",
      "Your willingness to ship imperfect code and improve it based on real feedback is actually the smartest approach.",
      "You understand that user feedback on working software beats theoretical discussions about unbuilt software.",
      "Your decisiveness prevents the analysis paralysis that kills more projects than bad code ever does.",
      "You bring a healthy impatience to teams that would otherwise overthink everything.",
      "Your ability to unblock yourself and others keeps projects on track when perfectionism would stall them.",
      "You have an accurate sense of what 'done' looks like, and you drive relentlessly toward it.",
      "Your pragmatic approach to AI tools — just use them and move on — actually gets more value from them than over-thinking it.",
      "You demonstrate that momentum is one of the most powerful forces in software development.",
      "Your willingness to make reversible decisions quickly is a genuine competitive advantage.",
      "You understand that most code will be changed or replaced anyway, so obsessing over it is wasteful.",
      "Your focus on outcomes over process makes you the most effective person in many meetings.",
      "You bring a refreshing honesty about what's important — working software that solves real problems.",
      "Your speed to deployment means you get real-world data faster, leading to better-informed decisions.",
      "You have the courage to ship, which is more rare and more valuable than most people realize.",
      "Your approach minimizes work-in-progress, which is actually one of the most important factors in team productivity.",
      "You understand that the cost of delay often exceeds the cost of imperfection.",
      "Your ability to say 'this is good enough, let's ship' saves teams from the trap of endless refinement.",
      "You bring a startup energy that keeps teams focused on delivering value instead of polishing details.",
      "Your practical mindset helps teams avoid over-engineering solutions for problems that might not even materialize.",
      "You're the person who turns plans into reality, and every team needs at least one of you.",
      "Your instinct for when to cut scope and ship is genuinely valuable and often right.",
      "You understand that software is never 'done,' so getting it out the door is the first step, not the last.",
      "Your velocity gives your team the luxury of iterating quickly based on real user behavior.",
      "You have the rare combination of confidence and adaptability — you ship fast and correct course fast.",
      "Your approach to development acknowledges a truth that many engineers resist: perfect is the enemy of shipped.",
      "You create a bias toward action that's contagious and makes entire teams more productive.",
      "Your pragmatism under pressure is exactly what's needed during crunch time and critical deadlines.",
      "You understand that most decisions are two-way doors, and your willingness to walk through them quickly is an asset.",
      "Your ability to deliver consistently, even if imperfectly, builds trust with stakeholders in a way that promises of future perfection never do.",
      "You keep the feedback loop short, which means you learn and adapt faster than developers who batch their releases.",
      "Your no-nonsense approach to development is exactly what early-stage products need to survive.",
      "You have a clarity about priorities that many engineers struggle to develop, even after years of experience.",
      "Your shipping cadence keeps the team energized — there's nothing more motivating than seeing your work in production.",
      "You demonstrate that good judgment about what to build is more valuable than perfection in how you build it.",
      "Your ability to assess risk quickly and act accordingly is a form of engineering maturity.",
      "You understand that the first version is for learning, not for perfection, and you optimize for learning.",
      "Your commitment to progress over perfection produces real results that stakeholders can see and appreciate.",
      "You're the developer who turns 'we should do this someday' into 'this is live now'.",
      "Your approach recognizes that working software is the primary measure of progress, and you optimize for it.",
      "You bring a healthy urgency that reminds teams why they're building in the first place — to deliver value.",
    ],
  },
}

/**
 * Get the full personality profile for a vibe label.
 * Picks one random roast and one random compliment deterministically
 * based on a seed (overall vibe score) so they stay consistent per upload.
 */
export function getPersonalityProfile(
  label: VibeLabel,
): PersonalityProfile & { selectedRoast: string; selectedCompliment: string } {
  const profile = PROFILES[label]
  const roastIndex = Math.floor(Math.random() * profile.roasts.length)
  const complimentIndex = Math.floor(Math.random() * profile.compliments.length)

  return {
    ...profile,
    selectedRoast: profile.roasts[roastIndex],
    selectedCompliment: profile.compliments[complimentIndex],
  }
}
